'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Icon} from './icons';

const freshness=[['Core','800','ms','At least two fresh agreeing sources; default deviation bound of 50 bps.'],['Stocks','2','sec','Verified bid/ask and a second source, with exchange session checks.'],['Listed Small Caps','5','sec','At least three licensed feeds aggregated inside an attested enclave.'],['OTC tiers','60','sec','OTC reports use their specified tier window and tighter liquidity limits.']];
const sessions=[['Regular','Full liquidity-class limits apply with fresh in-session reports.'],['Pre / post','Leverage is lower and spreads widen outside regular hours.'],['Overnight','The overnight tier keeps tighter leverage and session-aware price bounds.'],['Closed','New entries pause. References are labelled last close.']];
export function MarketBento(){const [feed,setFeed]=useState(0);const [session,setSession]=useState(0);return <div className="market-bento">
 <div className="bento-meadow"><img src="/photos/golden-wildflower-meadow.webp" alt="A sunlit wildflower meadow" loading="lazy"/><div><span className="eyebrow">A SHARED FOUNDATION</span><h3>One balance.<br/><em>Room to grow.</em></h3><p>USDC is the common collateral across every product family.</p></div></div>
 <article className="bento-freshness"><span className="eyebrow">ORACLE FRESHNESS</span><div className="freshness-headline" key={feed}>{freshness[feed][1]}<span>{freshness[feed][2]}</span></div><p aria-live="polite">{freshness[feed][3]}</p><div className="freshness-ledger" aria-label="Select an oracle family">{freshness.map(([name,time,unit],i)=><button key={name} aria-pressed={feed===i} onClick={()=>setFeed(i)}><span>{name}</span><strong>{time} {unit}</strong></button>)}</div></article>
 <article className="bento-price"><Icon name="oracle" size={28} botanical/><h3>A price with provenance.</h3><p>Signed reports carry a timestamp, source agreement, an uncertainty band and the market’s current state.</p><span className="bento-caption">VERIFY / BOUND / EXECUTE</span></article>
 <article className="bento-session"><span className="eyebrow">SESSION-AWARE EXPOSURE</span><h3>The market sets<br/><em>the rhythm.</em></h3><div className="session-ribbon" aria-label="Explore market sessions">{sessions.map(([name],i)=><button key={name} aria-pressed={session===i} onClick={()=>setSession(i)}>{name}</button>)}</div><p key={session} aria-live="polite">{sessions[session][1]}</p></article>
 </div>}

const rulebook=[
 {title:'Set the spending boundaries',body:'A maximum per order and a daily budget are checked when the delegate acts.',detail:'The signer’s authority expires at the time you choose. Budgets belong to the authorized margin-account policy.',icon:'budget' as const},
 {title:'Choose the product families',body:'Allow the markets your strategy needs, with a separate permission for each family.',detail:'Seven product bits cover Core, Stocks, Small Caps, Squared, Factors, Tickets and Twins. Withdrawal authority stays disabled by default.',icon:'grid' as const},
 {title:'Keep a way to stop',body:'Revoke a delegate or use the kill switch to stop new agent actions.',detail:'A session signer can work within your policy without taking ownership of your wallet or receiving your private key.',icon:'custody' as const},
];
export function AgentRulebook(){return <section className="agent-rulebook section"><div className="rulebook-intro"><div className="eyebrow">YOUR MANDATE, IN WRITING</div><h2>Give direction.<br/><em>Keep control.</em></h2><p>Define the boundaries before an agent makes its first move.</p><Link className="btn dark" href="/dashboard/?view=agents">Set your rulebook</Link></div><div className="rulebook-folds">{rulebook.map((r,i)=><details key={r.title} open={i===0}><summary><span className="rulebook-number">0{i+1}</span><h3>{r.title}</h3><Icon name="plus" size={19}/></summary><div className="rulebook-answer"><Icon name={r.icon} size={30} botanical/><div><p>{r.body}</p><p>{r.detail}</p></div></div></details>)}</div></section>}

export function ProtocolTimeline({rules}: {rules:string[][]}){return <section className="protocol-ledger section"><div className="protocol-ledger-intro"><div className="eyebrow">THE RULES THAT TRAVEL WITH YOU</div><h2>A clearer path.<br/><em>At every step.</em></h2><p>Price, authority, custody and risk each have a defined boundary.</p><div className="ledger-seal"><Icon name="shield" size={38} botanical/><span>VERIFICATION<br/>BEFORE EXECUTION</span></div></div><ol className="protocol-timeline">{rules.map(([n,title,body])=><li key={n}><span className="timeline-number">{n}</span><details open={n==='01'}><summary><h3>{title}</h3><Icon name="plus" size={18}/></summary><p>{body}</p></details></li>)}</ol></section>}

export function InstrumentMechanics({facts}: {facts:{label:string;body:string}[]}){return <div className="instrument-editorial">{facts.map((f,i)=><article key={f.label}><span className="editorial-number">0{i+1}</span><details open={i===0}><summary><h3>{f.label}</h3><Icon name="plus" size={18}/></summary><p>{f.body}</p></details></article>)}</div>}
